//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SMS_Test.com.suresms.api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SureSMS_SOAP_ServiceSoap", Namespace="api.suresms.com/soap/v1")]
    public partial class SureSMS_SOAP_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadUserBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadCoverageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SureSMS_SOAP_Service() {
            this.Url = global::SMS_Test.Properties.Settings.Default.SMS_Test_com_suresms_api_SureSMS_SOAP_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event ReadUserBalanceCompletedEventHandler ReadUserBalanceCompleted;
        
        /// <remarks/>
        public event CreateMessageCompletedEventHandler CreateMessageCompleted;
        
        /// <remarks/>
        public event ReadMessageCompletedEventHandler ReadMessageCompleted;
        
        /// <remarks/>
        public event ReadMessageStatusCompletedEventHandler ReadMessageStatusCompleted;
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event ReadPriceCompletedEventHandler ReadPriceCompleted;
        
        /// <remarks/>
        public event ReadCoverageCompletedEventHandler ReadCoverageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ValidateUser", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public response ValidateUser(string AccountName, string AccountPassword) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        AccountName,
                        AccountPassword});
            return ((response)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string AccountName, string AccountPassword) {
            this.ValidateUserAsync(AccountName, AccountPassword, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string AccountName, string AccountPassword, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        AccountName,
                        AccountPassword}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ReadUserBalance", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public userbalance ReadUserBalance(string AccountName, string AccountPassword) {
            object[] results = this.Invoke("ReadUserBalance", new object[] {
                        AccountName,
                        AccountPassword});
            return ((userbalance)(results[0]));
        }
        
        /// <remarks/>
        public void ReadUserBalanceAsync(string AccountName, string AccountPassword) {
            this.ReadUserBalanceAsync(AccountName, AccountPassword, null);
        }
        
        /// <remarks/>
        public void ReadUserBalanceAsync(string AccountName, string AccountPassword, object userState) {
            if ((this.ReadUserBalanceOperationCompleted == null)) {
                this.ReadUserBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadUserBalanceOperationCompleted);
            }
            this.InvokeAsync("ReadUserBalance", new object[] {
                        AccountName,
                        AccountPassword}, this.ReadUserBalanceOperationCompleted, userState);
        }
        
        private void OnReadUserBalanceOperationCompleted(object arg) {
            if ((this.ReadUserBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadUserBalanceCompleted(this, new ReadUserBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/CreateMessage", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public response CreateMessage(string AccountName, string AccountPassword, message Message) {
            object[] results = this.Invoke("CreateMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        Message});
            return ((response)(results[0]));
        }
        
        /// <remarks/>
        public void CreateMessageAsync(string AccountName, string AccountPassword, message Message) {
            this.CreateMessageAsync(AccountName, AccountPassword, Message, null);
        }
        
        /// <remarks/>
        public void CreateMessageAsync(string AccountName, string AccountPassword, message Message, object userState) {
            if ((this.CreateMessageOperationCompleted == null)) {
                this.CreateMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMessageOperationCompleted);
            }
            this.InvokeAsync("CreateMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        Message}, this.CreateMessageOperationCompleted, userState);
        }
        
        private void OnCreateMessageOperationCompleted(object arg) {
            if ((this.CreateMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMessageCompleted(this, new CreateMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ReadMessage", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public message ReadMessage(string AccountName, string AccountPassword, string MessageID) {
            object[] results = this.Invoke("ReadMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID});
            return ((message)(results[0]));
        }
        
        /// <remarks/>
        public void ReadMessageAsync(string AccountName, string AccountPassword, string MessageID) {
            this.ReadMessageAsync(AccountName, AccountPassword, MessageID, null);
        }
        
        /// <remarks/>
        public void ReadMessageAsync(string AccountName, string AccountPassword, string MessageID, object userState) {
            if ((this.ReadMessageOperationCompleted == null)) {
                this.ReadMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMessageOperationCompleted);
            }
            this.InvokeAsync("ReadMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID}, this.ReadMessageOperationCompleted, userState);
        }
        
        private void OnReadMessageOperationCompleted(object arg) {
            if ((this.ReadMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMessageCompleted(this, new ReadMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ReadMessageStatus", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public messagestatus ReadMessageStatus(string AccountName, string AccountPassword, string MessageID) {
            object[] results = this.Invoke("ReadMessageStatus", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID});
            return ((messagestatus)(results[0]));
        }
        
        /// <remarks/>
        public void ReadMessageStatusAsync(string AccountName, string AccountPassword, string MessageID) {
            this.ReadMessageStatusAsync(AccountName, AccountPassword, MessageID, null);
        }
        
        /// <remarks/>
        public void ReadMessageStatusAsync(string AccountName, string AccountPassword, string MessageID, object userState) {
            if ((this.ReadMessageStatusOperationCompleted == null)) {
                this.ReadMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMessageStatusOperationCompleted);
            }
            this.InvokeAsync("ReadMessageStatus", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID}, this.ReadMessageStatusOperationCompleted, userState);
        }
        
        private void OnReadMessageStatusOperationCompleted(object arg) {
            if ((this.ReadMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMessageStatusCompleted(this, new ReadMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/DeleteMessage", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public response DeleteMessage(string AccountName, string AccountPassword, string MessageID) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID});
            return ((response)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(string AccountName, string AccountPassword, string MessageID) {
            this.DeleteMessageAsync(AccountName, AccountPassword, MessageID, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(string AccountName, string AccountPassword, string MessageID, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        AccountName,
                        AccountPassword,
                        MessageID}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ReadPrice", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public price ReadPrice(string AccountName, string AccountPassword, message[] Messages) {
            object[] results = this.Invoke("ReadPrice", new object[] {
                        AccountName,
                        AccountPassword,
                        Messages});
            return ((price)(results[0]));
        }
        
        /// <remarks/>
        public void ReadPriceAsync(string AccountName, string AccountPassword, message[] Messages) {
            this.ReadPriceAsync(AccountName, AccountPassword, Messages, null);
        }
        
        /// <remarks/>
        public void ReadPriceAsync(string AccountName, string AccountPassword, message[] Messages, object userState) {
            if ((this.ReadPriceOperationCompleted == null)) {
                this.ReadPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadPriceOperationCompleted);
            }
            this.InvokeAsync("ReadPrice", new object[] {
                        AccountName,
                        AccountPassword,
                        Messages}, this.ReadPriceOperationCompleted, userState);
        }
        
        private void OnReadPriceOperationCompleted(object arg) {
            if ((this.ReadPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadPriceCompleted(this, new ReadPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("api.suresms.com/soap/v1/ReadCoverage", RequestNamespace="api.suresms.com/soap/v1", ResponseNamespace="api.suresms.com/soap/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CoverageItem[] ReadCoverage(string AccountName, string AccountPassword) {
            object[] results = this.Invoke("ReadCoverage", new object[] {
                        AccountName,
                        AccountPassword});
            return ((CoverageItem[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadCoverageAsync(string AccountName, string AccountPassword) {
            this.ReadCoverageAsync(AccountName, AccountPassword, null);
        }
        
        /// <remarks/>
        public void ReadCoverageAsync(string AccountName, string AccountPassword, object userState) {
            if ((this.ReadCoverageOperationCompleted == null)) {
                this.ReadCoverageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadCoverageOperationCompleted);
            }
            this.InvokeAsync("ReadCoverage", new object[] {
                        AccountName,
                        AccountPassword}, this.ReadCoverageOperationCompleted, userState);
        }
        
        private void OnReadCoverageOperationCompleted(object arg) {
            if ((this.ReadCoverageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCoverageCompleted(this, new ReadCoverageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class response {
        
        private int responseCodeField;
        
        private string responseTextField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class CoverageItem {
        
        private int countrycodeField;
        
        private string countryNameField;
        
        private bool numericalSenderIDField;
        
        private bool alphanumericalSenderIDField;
        
        private bool deliveryReportField;
        
        private bool flashMessageField;
        
        /// <remarks/>
        public int Countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                this.countrycodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public bool NumericalSenderID {
            get {
                return this.numericalSenderIDField;
            }
            set {
                this.numericalSenderIDField = value;
            }
        }
        
        /// <remarks/>
        public bool AlphanumericalSenderID {
            get {
                return this.alphanumericalSenderIDField;
            }
            set {
                this.alphanumericalSenderIDField = value;
            }
        }
        
        /// <remarks/>
        public bool DeliveryReport {
            get {
                return this.deliveryReportField;
            }
            set {
                this.deliveryReportField = value;
            }
        }
        
        /// <remarks/>
        public bool FlashMessage {
            get {
                return this.flashMessageField;
            }
            set {
                this.flashMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class price {
        
        private double price1Field;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price")]
        public double price1 {
            get {
                return this.price1Field;
            }
            set {
                this.price1Field = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class messagestatus {
        
        private string messageIDField;
        
        private int statusCodeField;
        
        private string statusTextField;
        
        private System.DateTime receivedOnUTCDateTimeField;
        
        private System.DateTime requiredDeliveryOnUTCDateTimeField;
        
        private System.DateTime dispatchedOnUTCDateTimeField;
        
        private System.DateTime deliveredOnUTCDateTimeField;
        
        private System.DateTime lastKnownStatusOnUTCDateTimeField;
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedOnUTCDateTime {
            get {
                return this.receivedOnUTCDateTimeField;
            }
            set {
                this.receivedOnUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequiredDeliveryOnUTCDateTime {
            get {
                return this.requiredDeliveryOnUTCDateTimeField;
            }
            set {
                this.requiredDeliveryOnUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DispatchedOnUTCDateTime {
            get {
                return this.dispatchedOnUTCDateTimeField;
            }
            set {
                this.dispatchedOnUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveredOnUTCDateTime {
            get {
                return this.deliveredOnUTCDateTimeField;
            }
            set {
                this.deliveredOnUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastKnownStatusOnUTCDateTime {
            get {
                return this.lastKnownStatusOnUTCDateTimeField;
            }
            set {
                this.lastKnownStatusOnUTCDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class message {
        
        private string toPhonenumbersField;
        
        private string messageTextField;
        
        private string messageIDField;
        
        private string senderIDField;
        
        private bool sendAsFlashField;
        
        private string hasCallBackURLField;
        
        private System.DateTime requiredDeliveryUTCDateTimeField;
        
        private bool scheduleDailyField;
        
        private bool scheduleDailyExceptWeekendField;
        
        private bool scheduleWeeklyField;
        
        private bool scheduleMonthlyField;
        
        private bool scheduleYearlyField;
        
        /// <remarks/>
        public string ToPhonenumbers {
            get {
                return this.toPhonenumbersField;
            }
            set {
                this.toPhonenumbersField = value;
            }
        }
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        public bool SendAsFlash {
            get {
                return this.sendAsFlashField;
            }
            set {
                this.sendAsFlashField = value;
            }
        }
        
        /// <remarks/>
        public string HasCallBackURL {
            get {
                return this.hasCallBackURLField;
            }
            set {
                this.hasCallBackURLField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequiredDeliveryUTCDateTime {
            get {
                return this.requiredDeliveryUTCDateTimeField;
            }
            set {
                this.requiredDeliveryUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleDaily {
            get {
                return this.scheduleDailyField;
            }
            set {
                this.scheduleDailyField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleDailyExceptWeekend {
            get {
                return this.scheduleDailyExceptWeekendField;
            }
            set {
                this.scheduleDailyExceptWeekendField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleWeekly {
            get {
                return this.scheduleWeeklyField;
            }
            set {
                this.scheduleWeeklyField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleMonthly {
            get {
                return this.scheduleMonthlyField;
            }
            set {
                this.scheduleMonthlyField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleYearly {
            get {
                return this.scheduleYearlyField;
            }
            set {
                this.scheduleYearlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="api.suresms.com/soap/v1")]
    public partial class userbalance {
        
        private double balanceField;
        
        private string currencyField;
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadUserBalanceCompletedEventHandler(object sender, ReadUserBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadUserBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadUserBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public userbalance Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((userbalance)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateMessageCompletedEventHandler(object sender, CreateMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadMessageCompletedEventHandler(object sender, ReadMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public message Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((message)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadMessageStatusCompletedEventHandler(object sender, ReadMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public messagestatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((messagestatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadPriceCompletedEventHandler(object sender, ReadPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public price Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((price)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadCoverageCompletedEventHandler(object sender, ReadCoverageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCoverageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCoverageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CoverageItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CoverageItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591